services:
#  snhw_nginx:
#    image: nginx
#    container_name: snhw_nginx
#    ports:
#      - 8080:80
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - snhw_api
#    networks:
#      - snhw_network
  snhw_db:
    image: postgres:latest
    container_name: snhw_pg
    environment:
      - POSTGRES_USER=baeldung
      - POSTGRES_PASSWORD=baeldung
      - POSTGRES_DB=baeldung
    volumes:
      - snhw_pgdata:/var/lib/postgresql/data
      - ./sql_init_tables:/docker-entrypoint-initdb.d
      - ./sql_init_data/people.interests.csv:/people.interests.csv
      - ./sql_init_data/people.csv:/people.csv
    ports:
      - 5432:5432
    networks:
      - snhw_network
  snhw_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: snhw_pgadmin
    ports:
      - 5454:80/tcp
    depends_on:
      - snhw_db
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@baeldung.com
      - PGADMIN_DEFAULT_PASSWORD=baeldung
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - snhw_pgadmindata:/var/lib/pgadmin
  snhw_api:
    container_name: snhw_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5054:8080
    depends_on:
      - snhw_db
    links:
      - snhw_db
    environment:
      - CONNECTIONSTRINGS__DEFAULT=User ID=baeldung;Password=baeldung;Host=snhw_db;Port=5432;Database=baeldung;
    networks:
      - snhw_network
#  snhw_influxdb:
#    image: influxdb
#    ports:
#      - 8086:8086
#    container_name: snhw_influxdb
#    security_opt:
#        - no-new-privileges:true
#    restart: unless-stopped
#    volumes:
#      - $DOCKERDIR/appdata/influxdb2/config:/etc/influxdb2
#      - $DOCKERDIR/appdata/influxdb2/db:/var/lib/influxdb2
#    networks:
#      - snhw_network
#  snhw_grafana:
#    image: grafana/grafana-oss
#    ports:
#      - 3000:3000
#    container_name: snhw_grafana
#    depends_on:
#      - snhw_influxdb
#    volumes:
#      - snhw_grafana:/var/lib/grafana
#    networks:
#      - snhw_network
volumes:
  snhw_pgdata:
  snhw_apidata:
  snhw_pgadmindata:
  snhw_grafana:
  snhw_influxdb:
networks:
  snhw_network:
    driver: bridge